FROM node:20-alpine AS builder
WORKDIR /app
COPY simulator/package.json simulator/tsconfig.json ./
RUN npm install
COPY simulator/src ./src
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./
ENV NODE_ENV=production
ENV SERVICE_NAME=simulator
CMD ["node", "dist/index.js"]
